MQTT:
  HOST_NAME: "pc_cam1"

POST_PROC:
  BIN_THR: 180
  KERNEL: 21
  CIRC_THR: 0.8
  W_H_DIFF: 20
  BALL_SIZE: 100
  AREA_THR: 80

CAMERA:
  FPS: 60
  EXPOSURE: 6000
  HARD_TRIGG: false

CALIB:
  ROWS: 6
  COLS: 9

SERVER:
  SEND_IMG: true

SAVE_CALIB: true
