MQTT:
  HOST_NAME: "camera1"

POST_PROC:
  BIN_THR: 180
  KERNEL: 21
  CIRC_THR: 0.8
  W_H_DIFF: 20
  BALL_SIZE: 100
  AREA_THR: 80

CAMERA:
  FPS: 60
  EXPOSURE: 12000
  HARD_TRIGG: false

CALIB:
  ROWS: 6
  COLS: 9
  SQUARE_SIZE: 1000

SAVE_CALIB: true
